### ISSUE TITLE
Unexpected warning

### ISSUE THREAD

**Issue by dcleal** [aws/aws-iot-device-sdk-java#12]
Hi, 

things are working for me, but I see warnings like this:

Dec 13, 2016 11:30:29 AM com.amazonaws.services.iot.client.shadow.AwsIotDeviceCommandManager onCommandAck
WARNING: Unknown command received from topic $aws/things/3d621cd1-aeac-4fa3-8a7f-560ebca7473f/shadow/update/accepted

The problem seems to originate in AwsIotDeviceCommandManager, line 268, where it returns null because it can't find a particular command in pendingCommands. Is this normal? Everything seems to work as I expect otherwise.

**Comment by liuszeng** [comment]
Hi @dcleal ,

Thank you very much for your interest in AWS IoT Java SDK!

The AWS IoT shadow features publish/subscribe based MQTT request/response model. For a typical shadow operation, the client will need to publish the request payload and subscribe to the response topics and receive the server response from there. As a way of tracking the response, the SDK will generate client token for each shadow request and check on that token on each incoming response so as to trigger the corresponding command ack. See the details here:
https://github.com/aws/aws-iot-device-sdk-java/blob/master/aws-iot-device-sdk-java/src/main/java/com/amazonaws/services/iot/client/shadow/AwsIotDeviceCommandManager.java#L286

The issue you mentioned could be caused by the fact that the SDK client received some responses from the accepted/rejected topic which are requested from another end, not from this SDK client. If the recevied the response does not contain the client token it issued, the warning message will be generated.

Are you subscribing to the accepted/rejected shadow response topics using the SDK and trying to operate on the same shadow from another end?

Thanks,
Liusu

**Comment by dcleal** [comment]
No, I don't think I am.

I am updating the 'desired' state of the shadow from the AWS end, of course, but based on what you say this shouldn't cause warnings? 

I'll try and whip up a small-scale example that I can post here (right now this is part of a large code base).

-Dave

**Comment by fengsongAWS** [comment]
Hi @dcleal ,
I think what Liusu means is that did you update the desired state and listen for the response from the same end? The client token would be different for different clients. Please feel free to post the code sample and see if it works.

Thanks,
Fengyi

**Comment by dcleal** [comment]
Yes, I think I understood what Liusu said. In my code, the desired state is updated by a lamda running on the server. My IoT thing doesn't update the desired state.

**Comment by fengsongAWS** [comment]
It seems you are updating the desired state from a lambda function on the server and at the same time, you are listening to the topics from another client. Is that true?

Thanks,
Fengyi
