### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by kenwdelong** [aws/aws-iot-device-sdk-java#19]
I cannot get my sdk to connect properly to AWS IoT, either with my own code or with the samples.  Here is my aws-iot-sdk-samples.properties file:

    # Client endpoint, e.g. <prefix>.iot.us-east-1.amazonaws.com
    clientEndpoint=xxx.iot.us-east-1.amazonaws.com

    # Client ID, unique client ID per connection
    clientId=thing1

    # Client certificate file
    certificateFile=/Users/Ken/workspace/IotTest/src/main/resources/certs/thing1/1215d8c24d-certificate.pem.crt

    # Client private key file
    privateKeyFile=/Users/Ken/workspace/IotTest/src/main/resources/certs/thing1/1215d8c24d-private.pem.key

    # Thing name
    thingName=thing1

The certs were generated in the IoT console.  They are active and have this policy attached:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "arn:aws:iot:us-east-1:123456789:topic/test/*"
    }
  ]
}
```

My endpoint has ACTIVE status.

This is the error I get locally:
```
[INFO] --- exec-maven-plugin:1.5.0:java (default-cli) @ aws-iot-device-sdk-java-samples ---
Feb 15, 2017 12:10:06 PM com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener onFailure
WARNING: Connect request failure
Connection lost (32109) - java.io.EOFException
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException
        at java.io.DataInputStream.readByte(DataInputStream.java:267)
        at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
        ... 1 more
```

Cloudwatch logs say 
`[INFO] EVENT:MQTT Client Connect MESSAGE:Connect Status: AUTHORIZATION_ERROR`

I think I'm using the SDK properly.  However, there doesn't seem to be a way to use the CA cert with the SDK (I used IoT's default root VeriSign cert).

Sorry for the noob question, but what am I missing here?

**Comment by liuszeng** [comment]
Hi @kenwdelong ,

Thank you very much for using AWS IoT Java SDK.

The issue here is with the IoT Policy attached to your certificate. There is a mismatch between the Action type and Resource type.

IoT Policy defines what kind of actions you can perform and what kind of resource you can access by presenting the certificate as your identity to the server. It has a mapping from action type to the corresponding type. You can find the type mapping here:
http://docs.aws.amazon.com/iot/latest/developerguide/action-resources.html

When you specify the action to be `*` in your policy, you are allowing all actions. As a result, you will need to specify the resource to be `*` so that it can be mapped to apply all the allowed actions. If you want a more restricted policy, you will need to define them separately, e.g., which client id is allowed to connect, which topic is allowed to publish, which topicFilter is allowed to subscribe, etc. You can try update your IoT Policy document and check if the issue still exists.

For more samples and guidance on AWS IoT Policy, you can check out the following documentation:
http://docs.aws.amazon.com/iot/latest/developerguide/connect-policy.html
http://docs.aws.amazon.com/iot/latest/developerguide/pub-sub-policy.html

Hope the above helps.

Thanks,
Liusu

**Comment by kenwdelong** [comment]
Holy cow, thank you!  That fixed it.  I was busy fiddling with the code!

**Comment by Akanksha-Gill** [comment]
Apr 13, 2018 11:51:27 AM com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener onFailure
WARNING: Connect request failure
Connection lost (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(Unknown Source)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
	... 1 more
How to solve this?
