### ISSUE TITLE
Is there any plan to upgrade to org.eclipse.paho.client.mqttv3 1.2.0?

### ISSUE THREAD

**Issue by HAKASHUN** [aws/aws-iot-device-sdk-java#38]
The latest version is 1.2.0.
Is there any plan to upgrade?

https://github.com/eclipse/paho.mqtt.java/releases

**Comment by chaurah** [comment]
Hi @HAKASHUN,
      We are working on this for the next release of the SDK. I will update and close this ticket when the release is out.

Please let us know if we can help further. Thank you for using AWS IoT.

Rahul

**Comment by HAKASHUN** [comment]
Thank you for your reply! 
I'm looking forward to the release.

**Comment by lagnat** [comment]
1.1.0 has a [reconnect deadlock](https://github.com/eclipse/paho.mqtt.java/commit/d97cc6946149261e312f773b9e0a1dc3708d90f8) bug that is fixed in 1.2.0.  Are there any known issues using 1.2.0 with Aws IoT 1.1.1?

**Comment by shmuelberezin** [comment]
I'm waiting for Paho 1.1.1 which includes a fix to [NullPointerException in receiveHandshakeResponse issue](https://github.com/eclipse/paho.mqtt.java/issues/234).
The fix is in Pull request [Adding connection checks to WebSocket Tests](https://github.com/eclipse/paho.mqtt.java/pull/263) which is included in version 1.1.1 (https://github.com/eclipse/paho.mqtt.java/compare/v1.1.0...v1.1.1).

1. Is it OK to change the Paho version to 1.1.1? are there any known issues with using this version with aws-iot-device-sdk-java?
2. What is the schedule for releasing a new version of aws-iot-device-sdk-java? The last version was released a year ago...

**Comment by maciejdzikowicki** [comment]
I was trying to use paho 1.2.0 and had this issue: https://github.com/aws/aws-iot-device-sdk-java/issues/70

**Comment by DavidOgunsAWS** [comment]
We have recently upgraded the Paho version to 1.2.2 from 1.2.1.
