### ISSUE TITLE
NullPointerException in receiveHandshakeResponse() missing upgrade header.

### ISSUE THREAD

**Issue by Encrypto34** [aws/aws-iot-device-sdk-java#5]
I received this exception multiple times when I disconnect and reconnect the internet on my computer. 
After this appears, the client can no longer receive push notifications. Is there anything I can do to prevent this without having to recompile the source code into my own library? Thanks.

**Error**: 

```
com.amazonaws.services.iot.client.core.AwsIotConnection$1 run
INFO: Connection is being retried
com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener onFailure
WARNING: Connect request failure
MqttException (0) - java.lang.NullPointerException
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.receiveHandshakeResponse(WebSocketHandshake.java:133)
        at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.execute(WebSocketHandshake.java:74)
        at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:77)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
        ... 1 more
```

**Code: (upgradeHeader is null)**

```
String upgradeHeader = (String) headerMap.get(HTTP_HEADER_UPGRADE);
if(!upgradeHeader.toLowerCase().contains(HTTP_HEADER_UPGRADE_WEBSOCKET)){
    throw new IOException("WebSocket Response header: Incorrect upgrade.");
}
```

**Steps to reproduce:**
- Connect the client
- Connection is successful
- Disconnect the internet (leave the client running)
- Wait a few minutes
- The client will attempt to reconnect and fail as expected.

```
...
com.amazonaws.services.iot.client.core.AwsIotConnection$1 run
INFO: Connection is being retried
com.amazonaws.services.iot.client.mqtt.AwsIotMqttConnectionListener onFailure
WARNING: Connect request failure
...
```
- Reconnect the internet.
- The exception above appears.
- The client will no longer receive push notifications.

**Comment by rongsaws** [comment]
Thanks for providing the detailed reproducing steps.  As you pointed out, the NPE was thrown by the Paho MQTT Java client, which was due to the WebSocket request being rejected by the server. Similar report was found in their GitHub repo (https://github.com/eclipse/paho.mqtt.java/issues/234). As mentioned in that GitHub issue, the exception type thrown could be improved, but the real reason in this case was because the signed URL used for the WebSocket upgrade request was expired during the reconnect process. While the WebSocket connection once established can last as long as 24 hours, the signed URL used for establishing the connection is only valid for few minutes. 

One quick fix for us is to regenerate the signed URL for every reconnect request, but the downside of it is the SDK has to store the AWS IAM access key and security key in memory for the entire time, so that they can be used to sign URLs when reconnect is needed. This is less desirable from security point of view as anyone is able to dump the application memory will be capable of extracting the credentials.

An alternative approach is to handle the connection retry externally. You can disable the automatic connection retry by calling AWSIotMqttClient:setMaxConnectionRetries(0), and override AWSIotMqttClient:onConnectionFailure() to listen to connection failure events. When a connection failure event is detected, you could create a new AWSIotMqttClient instance to restart the connection. This solution is also less ideal, but it gives you the opportunity to retrieve temporary or permanent IAM credentials through safe mechanisms. 

We'll also be looking into other possible ways of fixing this issue. Thanks again for reporting it to us.
