### ISSUE TITLE
Unhandled java.util.concurrent.RejectedExecutionException 

### ISSUE THREAD

**Issue by OctanMan** [aws/aws-iot-device-sdk-java#50]
I receive an unhandled `java.util.concurrent.RejectedExecutionException` when:
1. I set `client.setMaxConnectionRetries(2)`
2. I call `client.connect(10000)`
3. The connection fails - e.g. bad endpoint parameter
4. I call `client.connect(10000)` again

The issue appears to be similar to [this one](https://github.com/aws/aws-sdk-android/issues/113) with aws-sdk-android. 

`Exception in thread "main" java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@758c83d8 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@129b4fe2[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 5]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at com.amazonaws.services.iot.client.core.AbstractAwsIotClient.scheduleTimeoutTask(AbstractAwsIotClient.java:392)
	at com.amazonaws.services.iot.client.core.AwsIotCompletion.get(AwsIotCompletion.java:187)
	at com.amazonaws.services.iot.client.core.AbstractAwsIotClient.connect(AbstractAwsIotClient.java:112)
	at com.amazonaws.services.iot.client.AWSIotMqttClient.connect(AWSIotMqttClient.java:501)
	at com.amazonaws.services.iot.client.core.AbstractAwsIotClient.connect(AbstractAwsIotClient.java:101)
	at com.amazonaws.services.iot.client.AWSIotMqttClient.connect(AWSIotMqttClient.java:480)`

**Comment by liuszeng** [comment]
Hi @OctanMan ,

I am able to duplicate your issue on my side.

The problem here is, once the max connect retries are exhausted, the internal `ThreadPoolExecutor` is permanently shutdown. If you attempt to schedule a new task to a already-shut-down `ThreadPoolExecutor`, it will throw `RejectedExecutionException`.

The SDK handles retries automatically in the background for you. `connect(int timeout)` is a blocking call that will not return until it succeeds, fails or timeouts (See API docs [here](http://aws-iot-device-sdk-java-docs.s3-website-us-east-1.amazonaws.com/)). If you closely look at the log output, you will see that there are 2 connect attempts triggered in your first `connect` call, which is because the client is not able to connect successfully at the first time and does retries by itself. By the time you invoke the second `connect`, the max retries have already been exhausted, resulting in RejectedExecutionException.

I have created an internal tracker to better handle this runtime exception. Please stay tuned for future releases.

Thanks,
Liusu

**Comment by OctanMan** [comment]
Hi @liuszeng ,

Thanks for your quick response and explanation. I can see where the `ThreadPoolExecutor` is closed on line [418](https://github.com/aws/aws-iot-device-sdk-java/blob/master/aws-iot-device-sdk-java/src/main/java/com/amazonaws/services/iot/client/core/AbstractAwsIotClient.java#L418) of `AbstractAwsIotClient` in `onConnectionClosed()`, however, I can't see a field or method available to determine whether a client has been permanently closed. It's simple enough to extend the client and override `onConnectionClosed()` to capture this state (or otherwise change the behaviour) but it feels like something that should be exposed already.

Since the client is described as being [thread-safe](http://aws-iot-device-sdk-java-docs.s3-website-us-east-1.amazonaws.com/) my intention was to have multiple threads try and utilise a client at an arbitrary time in an arbitrary order. As well as extending the client,  I'll also take a look at the async connection method to see if that fits better with my design.

I look forward to seeing your enhancements in future releases.

Cheers
