### ISSUE TITLE
About AWS MQTT Client connection loss event and Clean Session

### ISSUE THREAD

**Issue by Jason-Gew** [aws/aws-iot-device-sdk-java#54]
Hi,

I have two questions for the AWS MQTT Java client. Since I read from the AWS guide [https://docs.aws.amazon.com/iot/latest/developerguide/protocols.html](url) that AWS MQTT broker does not support clean session = false, does it mean that once connection lost I have to re-subscribe to all the topics again?

Besides, is there any callback method we can invoke on connection lost? So that I will have the event triggered by the client instance.

Thanks
Jason

**Comment by liuszeng** [comment]
Hi @Jason-Gew ,

Thank you very much for your interest in AWS IoT Device SDK for Java.

A "clean session = false" means that the MQTT server will keep the context (client id, subscriptions, etc.) of the previous connection so that the client does not need to perform MQTT subscribes upon a reconnect. Currently, AWS IoT does not support that.

Fortunately, this is handled by the SDK. The SDK will auto-reconnect and auto-resubscribe to your previously subscribed topics. You do not need to specifically handle that by yourself.

As for disconnect callback, you should be able to find it here:
https://github.com/aws/aws-iot-device-sdk-java/blob/master/aws-iot-device-sdk-java/src/main/java/com/amazonaws/services/iot/client/AWSIotMqttClient.java#L1063

Hope the above helps. Please feel free to reopen the issue or create a new thread if you have more questions.

Thanks,
Liusu

**Comment by Jason-Gew** [comment]
Hi @liuszeng,

In my scenario, after the default retries over, it looks stopped keep retrying. After network comes back, it still remain not connected. If I manually let the it connect again, it actually did not subscribe to those previous topics.

Jason~

**Comment by liuszeng** [comment]
Hi @Jason-Gew ,

As of the current version, the SDK has a maximum number of retry attempts for auto-reconnect. If you exhausted the maximum number of retries, the SDK will throw a permanent error and you will not be able to use the same client instance again. You can get more details from the following issue:
https://github.com/aws/aws-iot-device-sdk-java/issues/50

Thanks,
Liusu
