### ISSUE TITLE
Multiple connections per client?

### ISSUE THREAD

**Issue by AndrewJudson** [aws/aws-iot-device-sdk-java#91]
There is a hard publish limit of 100 per second per connection - https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_iot. Is there a way to have a client to use multiple connections in order to get around this limit? Otherwise I'm going to have to maintain a pool of clients - and in that case, would each client need different secret, or can I instantiate the same client multiple times?

**Comment by justinboswell** [comment]
You would need a separate clientId for each connection, or else they'll disconnect each other. I would suggest instead requesting a service limit increase:

1) Go to https://console.aws.amazon.com/support/home#/ (log in if necessary)
2) Choose Service limit increase.
3) Complete the form. If this request is urgent, choose Phone as the method of contact instead of Web.
4) Choose Submit.

**Comment by AndrewJudson** [comment]
Ok, thanks. Unfortunately I don't think it can be adjusted - the documentation on the website says it is a hard limit (can't be adjusted) and our AWS contact said the same. Will look into creating separate client ids.

**Comment by justinboswell** [comment]
Oh, interesting, I'd not heard that before, but seems plausible, most uses of the IoT service aren't anywhere near that frequency. Good luck!
