### ISSUE TITLE
@AWSIotDeviceProperty annotation does not work in bidirectional way

### ISSUE THREAD

**Issue by fadikh** [aws/aws-iot-device-sdk-java#99]
SDK version: 1.3.0
The @AWSIotDeviceProperty does not work properly.
I have the following example:
public class MyDevice extends AWSIotDevice {

    public MyDevice(String thingName) {
        super(thingName);
    }

    @AWSIotDeviceProperty
    private float data;

    public float getData(){
        return data;
    }

    public void setData(float data){
        this.data = data;
    }
}

Lets assume that data value > 0 in the Shadow (simply from previous updates).
Once the created device attached to the client, data value changed to be 0.0 (or null for non primitive types)
After debugging, here some conclusions:
1 - Fields never synchronized by Shadow values, so they still have 0.0/null values, although
    allowUpdate has true value by default. (Setter function never called to sync attributes values).
2 - Shadow calls Getter function (getData) every 3 seconds to keep the shadow updates, but as described in the previous clause, fields still have 0.0/null values, so Shadow will be synced with 0.0/null values.
3 - Getter function called every 3 seconds and Setter functions never called.

Is there a way to let @AWSIotDeviceProperty works in a bidirectional way so MyDevice attributes  synced with Shadow values before Getter function called with 0.0/null ?

Thanks

**Comment by graebm** [comment]
The `@AWSIotDeviceProperty` are an attempt to make shadows easer to use. Their logic goes like this:
- On start, trust the value on the Device over the value in the Shadow.
- Every 3sec, check the value on the Device. If it's changed, report that to the Shadow.
  - 3sec timing can be tweaked via `AWSIotDevice.setReportInterval()`
- If the "desired" value changes in the Shadow, change it on the Device.

So your issue is that the starting value on the Device always overrides the the updated one in the Shadow. So the value has a default value every time the Device restarts.

One simple solution is to have the Device store its last-known-values in a file on disk. On startup, load that file and use those values. You should update those values if the "setter" runs, or if you change the value locally in any other way.

If you want to do things fancier, abandon the `@AWSIotDeviceProperty` and use the `update()` and `onShadowUpdate()` functions to manually reconcile differences between the "reported" and "desired" state.

**Comment by fadikh** [comment]
Thank you for your reply.
It still not clear for me, according to the following API documentation http://aws-iot-device-sdk-java-docs.s3-website-us-east-1.amazonaws.com/

allowUpdate allow updates from the shadow for the annotated attribute, but in my case annotated attributes never synced with the shadow, how do you explain that ?

Thanks
